apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-cicd-poc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nareshkumarjk02-sys/POC-07.git'
    targetRevision: HEAD
    path: helm/node-cicd-poc
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m